import type { Language } from "./types";

const en = {
  title: "Local usage", subtitle: "Browser messages accepted by ChatGPT on this device.",
  days7: "7 days", days30: "30 days", range: "Date range", refresh: "Refresh", total: "Accepted messages",
  today: "Today", week: "This week · Monday start", accepted: "Accepted", completed: "Completed", error: "Failed after acceptance",
  noOutcome: "No outcome",
  loading: "Reading local usage…", empty: "No local usage recorded yet", emptyBody: "New accepted browser messages will appear here. Earlier activity is not reconstructed.",
  unreadable: "Local usage could not be read", errorBody: "No totals are shown while the local record is unavailable. Try refreshing; if it still fails, see Storage and backups below before changing any files.",
  failed: "Could not load local usage", timezoneChanged: "Some historical days were recorded in another timezone. The displayed range uses the timezone below; historical day boundaries are retained.",
  daily: "Daily activity", details: "Daily details", date: "Date", tier: "Model / effort", lifetime: "Pro · all recorded activity",
  version: "Version", source: "Evidence", observed: "Observed", selfReported: "Self-reported", unknown: "Unknown", noPro: "No Pro messages recorded yet.",
  proUnknown: "Pro · version unknown", manualUnknown: "Zero Risk · unverified", since: "Recorded since", timezone: "Local timezone",
  boundary: "Local counts, not official remaining quota. Today and this week use the timezone shown; the week starts on Monday.",
  semantics: "Each accepted browser message counts once, including every multipart stage. A later failure does not remove it. Tool calls and pre-send failures are excluded. Duplicate callbacks do not add counts; a newly accepted resend does.",
  outcomeHelp: "No outcome means neither completion nor failure was recorded. The message may still be running, or its result may have been lost after a crash or storage error.",
  privacy: "Only local counts and model metadata are stored, never prompt text. Unverified versions are excluded from the two exact Pro cards.",
  storage: "Storage and backups",
  storageBody: "Updates keep usage/local-usage.json in the same core home, separate from versioned runtime files. The previous valid snapshot is kept as local-usage.json.bak. Daily detail is limited to 400 recorded dates; Pro lifetime totals are retained separately.",
  recovery: "After a downgrade, try the newer launcher first. Before restoring a backup, stop the launcher and core and save copies of both files. The backup may omit recent activity; it is not merged automatically. Changing the core home or deleting the usage folder does not preserve this history.",
  none: "No messages",
};
type UsageCopy = typeof en;
const zh: UsageCopy = {
  title: "本地用量", subtitle: "此设备上已被 ChatGPT 接受的浏览器消息。",
  days7: "7 天", days30: "30 天", range: "日期范围", refresh: "刷新", total: "已接受消息",
  today: "今天", week: "本周 · 周一开始", accepted: "已接受", completed: "已完成", error: "接受后失败",
  noOutcome: "未记录结果",
  loading: "正在读取本地用量…", empty: "尚无本地用量记录", emptyBody: "新接受的浏览器消息会显示在这里；不会补算此前的活动。",
  unreadable: "无法读取本地用量", errorBody: "本地记录不可用，暂不显示统计数字。可尝试刷新；若仍失败，请先查看下方「存储与备份」，不要直接删除文件。",
  failed: "无法加载本地用量", timezoneChanged: "部分历史日期按其他时区记录。当前范围使用下方时区，历史日期边界保持不变。",
  daily: "每日活动", details: "每日明细", date: "日期", tier: "模型 / 推理档位", lifetime: "Pro · 全部已记录活动",
  version: "版本", source: "依据", observed: "已观测", selfReported: "手动确认", unknown: "未知", noPro: "尚无 Pro 消息记录。",
  proUnknown: "Pro · 版本未知", manualUnknown: "Zero Risk · 未验证", since: "开始记录于", timezone: "本地时区",
  boundary: "这是本地计数，不是官方剩余额度。今天和本周均按所示时区计算；每周从周一开始。",
  semantics: "每条被接受的浏览器消息计一次，包括多段消息的每一段。接受后失败仍计入。工具调用和发送前失败不计入；重复回调不会重复计数，重新发送并获接受则另计一次。",
  outcomeHelp: "「未记录结果」表示既没有完成记录，也没有失败记录。消息可能仍在运行，也可能因程序退出或写入失败而缺少结果。",
  privacy: "仅保存本地计数和模型元数据，不保存提示词。未验证版本不计入两个精确 Pro 卡片。",
  storage: "存储与备份",
  storageBody: "更新保留同一核心数据目录中的 usage/local-usage.json，不随版本化运行时一起替换。前一次有效快照保存在 local-usage.json.bak。每日明细最多保留 400 个有记录的日期，Pro 累计另行保留。",
  recovery: "若降级后无法读取，先换回较新的启动器。恢复备份前，关闭启动器及核心进程，并另存两份文件。备份可能缺少最近的活动，不会自动合并。更换核心数据目录或删除 usage 文件夹，不会自动保留原有历史。",
  none: "无消息",
};
const ja: UsageCopy = {
  title: "ローカル使用量", subtitle: "このデバイスで ChatGPT に受け付けられたブラウザメッセージ。",
  days7: "7 日間", days30: "30 日間", range: "期間", refresh: "更新", total: "受付済みメッセージ",
  today: "今日", week: "今週 · 月曜日から", accepted: "受付済み", completed: "完了", error: "受付後に失敗",
  noOutcome: "結果未記録",
  loading: "ローカル使用量を読み込み中…", empty: "使用量はまだ記録されていません", emptyBody: "新しく受け付けられたブラウザメッセージが表示されます。過去の活動は復元されません。",
  unreadable: "ローカル使用量を読み取れません", errorBody: "ローカル記録を利用できないため、集計は表示していません。更新しても直らない場合は、ファイルを変更する前に下の「保存先とバックアップ」を確認してください。",
  failed: "ローカル使用量を読み込めませんでした", timezoneChanged: "一部の過去の日付は別のタイムゾーンで記録されています。表示範囲には下記のタイムゾーンを使用し、過去の日付区切りは維持します。",
  daily: "日別の活動", details: "日別の詳細", date: "日付", tier: "モデル / 推論レベル", lifetime: "Pro · 記録済みの全活動",
  version: "バージョン", source: "根拠", observed: "観測済み", selfReported: "自己申告", unknown: "不明", noPro: "Pro メッセージはまだ記録されていません。",
  proUnknown: "Pro · バージョン不明", manualUnknown: "Zero Risk · 未確認", since: "記録開始", timezone: "ローカルタイムゾーン",
  boundary: "ローカルの集計であり、公式の残り利用枠ではありません。今日と今週は表示されたタイムゾーンに従い、週は月曜日から始まります。",
  semantics: "複数パートの各段階を含め、受け付けられたメッセージを各 1 回計上します。受付後の失敗も含みます。ツール呼び出しや送信前の失敗は含みません。同じ通知の重複は数えませんが、再送が受け付けられた場合は別に計上します。",
  outcomeHelp: "「結果未記録」は完了も失敗も記録されていない状態です。処理中の場合のほか、終了や書き込みエラーで結果が残らなかった場合もあります。",
  privacy: "ローカル集計とモデル情報のみを保存し、プロンプト本文は保存しません。未確認バージョンは 2 つの Pro カードから除外します。",
  storage: "保存先とバックアップ",
  storageBody: "更新時も、同じコアデータディレクトリの usage/local-usage.json を保持します。バージョン別のランタイムとは別の保存先です。直前の有効な記録は local-usage.json.bak に残ります。日別の詳細は記録のある 400 日分までで、Pro の累計は別に保持します。",
  recovery: "旧版に戻して読めなくなった場合は、まず新しいランチャーを使ってください。復元前にランチャーとコアを停止し、両方のファイルを別途保存してください。バックアップには最新の活動がない場合があり、自動統合はしません。保存先の変更や usage フォルダの削除では履歴は引き継がれません。",
  none: "メッセージなし",
};
export function usageCopyFor(language: Language): UsageCopy {
  return language === "zh-CN" ? zh : language === "ja" ? ja : en;
}
